/*
 * Copyright 2024, TeamDev. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Redistribution and use in source and/or binary forms, with or without
 * modification, must retain the above copyright notice and the following
 * disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.spine.validation.java.point

import io.spine.protodata.ast.TypeName
import io.spine.protodata.render.CoordinatesFactory.Companion.nowhere
import io.spine.protodata.render.NonRepeatingInsertionPoint
import io.spine.text.TextCoordinates

/**
 * An insertion point at the place where users may add some extra validation code
 * to the one already generated by the standard [JavaValidationRenderer].
 *
 * Goes after all the standard validation checks but before returning/throwing
 * the resulting error.
 */
public class ExtraValidation(private val name: TypeName) : NonRepeatingInsertionPoint {

    override val label: String
        get() = "extra_validation:${name.typeUrl}"

    /**
     * Does not try to locate the point.
     *
     * This insertion point is printed as a part of the code
     * generated by the [JavaValidationRenderer].
     * So we never require locating it in code.
     * Thus, this method always returns [nowhere].
     */
    override fun locateOccurrence(text: String): TextCoordinates = nowhere
}
