#!/usr/bin/env bash

set -e

# Load environment variables for the case of execution from the Gradle build if they exist.
BASH_PROFILE=~/.bash_profile
BASH_RC=~/.bashrc

if [ -f ${BASH_PROFILE} ]; then
  echo "Using user's local bash profile."
  . ${BASH_PROFILE}
elif [ -f ${BASH_RC} ]; then
  echo "Using user's local bash runtime configuration."
  . ${BASH_RC}
fi

# Navigate to the folder with embed-code binaries.
cd _bin

# Use the Ubuntu binary for GitHub Actions and macOS binary in other cases.
if [ "$GITHUB_ACTIONS" = "true" ]; then
  echo "Running in GitHub Action."
  TOOL="./embed-code-ubuntu"
else
  echo "Running locally on macOS."
  TOOL="./embed-code-macos"
fi

# Check code samples.
"$TOOL" -config-path="../_settings/embed-code.yml" -mode="check"
