name: Code Embedding

on:
  pull_request:

jobs:
  build-embedded-code:
    name: Build embedded code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: zulu

      - run: ./gradlew :docs:buildAll

  check-embedded-samples:
    name: Match embedded and original code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: zulu

      - name: Check Embedding
        run: ./gradlew :docs:checkSamples
